import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Badge } from "@/components/ui/badge";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Link } from "wouter";
import { ArrowLeft, Sparkles, Brain, Zap, CheckCircle, AlertCircle, Loader2 } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

type AIModel = "gpt-4o" | "claude-3.5-sonnet" | "gemini-pro" | "med-gemma" | "clinical-bert";

interface ModelResponse {
  model: string;
  response: string;
  confidence: number;
  responseTime: number;
}

export default function AdvancedAI() {
  const { toast } = useToast();
  const [selectedModel, setSelectedModel] = useState<AIModel>("gpt-4o");
  const [prompt, setPrompt] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);
  const [responses, setResponses] = useState<ModelResponse[]>([]);
  const [compareMode, setCompareMode] = useState(false);

  const aiModels = {
    "gpt-4o": { name: "GPT-4o", category: "General AI", color: "blue" },
    "claude-3.5-sonnet": { name: "Claude 3.5 Sonnet", category: "General AI", color: "purple" },
    "gemini-pro": { name: "Gemini Pro", category: "General AI", color: "teal" },
    "med-gemma": { name: "Med-Gemma", category: "Medical AI", color: "green" },
    "clinical-bert": { name: "ClinicalBERT", category: "Medical AI", color: "orange" }
  };

  const handleGenerate = async () => {
    if (!prompt.trim()) {
      toast({
        title: "Error",
        description: "Please enter a prompt",
        variant: "destructive"
      });
      return;
    }

    setIsGenerating(true);
    
    // Simulate AI response (in production, call actual API)
    setTimeout(() => {
      const mockResponse: ModelResponse = {
        model: aiModels[selectedModel].name,
        response: `This is a simulated response from ${aiModels[selectedModel].name}. In production, this would connect to the actual AI model API and generate real medical-grade responses with HIPAA compliance.\n\nYour prompt: "${prompt}"\n\nThe response would include:\n- Medical accuracy validation\n- Clinical decision support\n- Evidence-based recommendations\n- Safety checks and contraindication alerts`,
        confidence: Math.random() * 30 + 70, // 70-100%
        responseTime: Math.random() * 2000 + 1000 // 1-3 seconds
      };

      setResponses([mockResponse]);
      setIsGenerating(false);
      
      toast({
        title: "Generation Complete",
        description: `Response generated by ${aiModels[selectedModel].name}`
      });
    }, 2000);
  };

  const handleCompareAll = async () => {
    if (!prompt.trim()) {
      toast({
        title: "Error",
        description: "Please enter a prompt",
        variant: "destructive"
      });
      return;
    }

    setIsGenerating(true);
    setCompareMode(true);

    // Simulate multi-AI comparison
    setTimeout(() => {
      const mockResponses: ModelResponse[] = Object.entries(aiModels).map(([key, model]) => ({
        model: model.name,
        response: `Simulated response from ${model.name} for: "${prompt}". This model specializes in ${model.category.toLowerCase()} tasks.`,
        confidence: Math.random() * 30 + 70,
        responseTime: Math.random() * 2000 + 1000
      }));

      setResponses(mockResponses);
      setIsGenerating(false);

      toast({
        title: "Multi-AI Comparison Complete",
        description: `All ${mockResponses.length} models have responded`
      });
    }, 3000);
  };

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900 p-6">
      <div className="max-w-7xl mx-auto space-y-6">
        <Link href="/dashboard">
          <Button variant="ghost" className="mb-4" data-testid="button-back">
            <ArrowLeft className="w-4 h-4 mr-2" />
            Back to Dashboard
          </Button>
        </Link>

        {/* Header */}
        <Card className="border-2 border-blue-400 bg-gradient-to-r from-blue-50 to-purple-50 dark:from-blue-950 dark:to-purple-950">
          <CardHeader>
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-3">
                <Brain className="w-10 h-10 text-blue-500" />
                <div>
                  <CardTitle className="text-3xl font-bold text-gray-900 dark:text-white">
                    Advanced AI Technologies
                  </CardTitle>
                  <CardDescription className="text-lg">
                    Multi-model AI platform with medical specialization
                  </CardDescription>
                </div>
              </div>
              <Badge className="bg-green-500 text-white font-bold text-sm px-3 py-1">
                ACTIVE
              </Badge>
            </div>
          </CardHeader>
        </Card>

        <Tabs defaultValue="generate" className="space-y-6">
          <TabsList className="grid w-full grid-cols-3">
            <TabsTrigger value="generate" data-testid="tab-generate">AI Generation</TabsTrigger>
            <TabsTrigger value="models" data-testid="tab-models">Available Models</TabsTrigger>
            <TabsTrigger value="compare" data-testid="tab-compare">Multi-AI Compare</TabsTrigger>
          </TabsList>

          {/* AI Generation Tab */}
          <TabsContent value="generate" className="space-y-4">
            <Card>
              <CardHeader>
                <CardTitle>AI-Powered Generation</CardTitle>
                <CardDescription>Generate healthcare content using advanced AI models</CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <div>
                  <label className="text-sm font-medium mb-2 block">Select AI Model</label>
                  <Select value={selectedModel} onValueChange={(value) => setSelectedModel(value as AIModel)}>
                    <SelectTrigger data-testid="select-model">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      {Object.entries(aiModels).map(([key, model]) => (
                        <SelectItem key={key} value={key}>
                          {model.name} ({model.category})
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>

                <div>
                  <label className="text-sm font-medium mb-2 block">Enter Prompt</label>
                  <Textarea
                    data-testid="input-prompt"
                    placeholder="e.g., Generate a patient intake form for a cardiology clinic with HIPAA compliance..."
                    value={prompt}
                    onChange={(e) => setPrompt(e.target.value)}
                    rows={5}
                    className="resize-none"
                  />
                </div>

                <div className="flex gap-3">
                  <Button
                    data-testid="button-generate"
                    onClick={handleGenerate}
                    disabled={isGenerating}
                    className="flex-1"
                  >
                    {isGenerating ? (
                      <>
                        <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                        Generating...
                      </>
                    ) : (
                      <>
                        <Sparkles className="w-4 h-4 mr-2" />
                        Generate with {aiModels[selectedModel].name}
                      </>
                    )}
                  </Button>
                  <Button
                    data-testid="button-compare-all"
                    onClick={handleCompareAll}
                    disabled={isGenerating}
                    variant="outline"
                  >
                    <Zap className="w-4 h-4 mr-2" />
                    Compare All Models
                  </Button>
                </div>

                {/* Response Display */}
                {responses.length > 0 && (
                  <div className="space-y-4 mt-6">
                    <h3 className="font-semibold text-lg">
                      {compareMode ? "Multi-Model Comparison" : "AI Response"}
                    </h3>
                    {responses.map((resp, idx) => (
                      <Card key={idx} className="bg-gray-50 dark:bg-gray-800">
                        <CardHeader>
                          <div className="flex items-center justify-between">
                            <CardTitle className="text-base">{resp.model}</CardTitle>
                            <div className="flex items-center gap-2">
                              <Badge variant="outline" className="bg-green-100 text-green-800">
                                {resp.confidence.toFixed(1)}% Confidence
                              </Badge>
                              <Badge variant="outline">
                                {resp.responseTime.toFixed(0)}ms
                              </Badge>
                            </div>
                          </div>
                        </CardHeader>
                        <CardContent>
                          <p className="text-sm whitespace-pre-wrap text-gray-700 dark:text-gray-300">
                            {resp.response}
                          </p>
                        </CardContent>
                      </Card>
                    ))}
                  </div>
                )}
              </CardContent>
            </Card>
          </TabsContent>

          {/* Available Models Tab */}
          <TabsContent value="models" className="space-y-4">
            <div className="grid md:grid-cols-2 gap-4">
              {Object.entries(aiModels).map(([key, model]) => (
                <Card key={key} className={`border-2 border-${model.color}-400`}>
                  <CardHeader>
                    <CardTitle className="flex items-center justify-between">
                      {model.name}
                      <Badge className={`bg-${model.color}-500 text-white`}>
                        {model.category}
                      </Badge>
                    </CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className="space-y-3">
                      <div className="flex items-center gap-2">
                        <CheckCircle className="w-4 h-4 text-green-600" />
                        <span className="text-sm">
                          {model.category === "Medical AI" ? "Medical domain expertise" : "General purpose AI"}
                        </span>
                      </div>
                      <div className="flex items-center gap-2">
                        <CheckCircle className="w-4 h-4 text-green-600" />
                        <span className="text-sm">HIPAA compliant processing</span>
                      </div>
                      <div className="flex items-center gap-2">
                        <CheckCircle className="w-4 h-4 text-green-600" />
                        <span className="text-sm">Real-time generation</span>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          </TabsContent>

          {/* Multi-AI Compare Tab */}
          <TabsContent value="compare" className="space-y-4">
            <Card>
              <CardHeader>
                <CardTitle>Multi-AI Verification System</CardTitle>
                <CardDescription>
                  Compare responses from multiple AI models simultaneously for enhanced accuracy and safety
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="grid md:grid-cols-3 gap-4">
                  <Card className="bg-blue-50 dark:bg-blue-950 border-blue-200">
                    <CardContent className="p-4">
                      <Brain className="w-8 h-8 text-blue-500 mb-2" />
                      <h4 className="font-semibold mb-1">5 AI Models</h4>
                      <p className="text-sm text-gray-600 dark:text-gray-400">
                        Compare responses from all available models
                      </p>
                    </CardContent>
                  </Card>

                  <Card className="bg-green-50 dark:bg-green-950 border-green-200">
                    <CardContent className="p-4">
                      <CheckCircle className="w-8 h-8 text-green-500 mb-2" />
                      <h4 className="font-semibold mb-1">Consensus Verification</h4>
                      <p className="text-sm text-gray-600 dark:text-gray-400">
                        Identify agreement across models
                      </p>
                    </CardContent>
                  </Card>

                  <Card className="bg-purple-50 dark:bg-purple-950 border-purple-200">
                    <CardContent className="p-4">
                      <Zap className="w-8 h-8 text-purple-500 mb-2" />
                      <h4 className="font-semibold mb-1">Safety Critical</h4>
                      <p className="text-sm text-gray-600 dark:text-gray-400">
                        Triple-check medical responses
                      </p>
                    </CardContent>
                  </Card>
                </div>

                <div className="bg-yellow-50 dark:bg-yellow-950 border-2 border-yellow-400 rounded-lg p-4">
                  <div className="flex items-start gap-3">
                    <AlertCircle className="w-5 h-5 text-yellow-600 flex-shrink-0 mt-0.5" />
                    <div>
                      <h4 className="font-semibold text-yellow-900 dark:text-yellow-100 mb-1">
                        Use Case: Safety-Critical Medical Applications
                      </h4>
                      <p className="text-sm text-yellow-800 dark:text-yellow-200">
                        Multi-AI verification is recommended for clinical decision support, medication recommendations,
                        and patient safety applications where accuracy is paramount.
                      </p>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>
          </TabsContent>
        </Tabs>
      </div>
    </div>
  );
}
