import { Organization, Contract } from "@shared/schema";

export interface LegalDocumentOptions {
  organizationType: string;
  jurisdiction: string;
  complianceRequirements: string[];
  dataProcessing: boolean;
  aiUsage: boolean;
  internationalOperations: boolean;
  customClauses?: string[];
}

export class LegalDocumentService {
  // Generate dynamic Terms of Service based on organization specifics
  static generateTermsOfService(organization: Organization, contract: Contract): string {
    const currentDate = new Date().toLocaleDateString();
    const jurisdiction = this.getJurisdiction(organization.state, organization.country);
    const complianceSection = this.generateComplianceSection(organization.complianceNeeds);
    const dataProcessingSection = this.generateDataProcessingSection(organization);
    const aiUsageSection = this.generateAIUsageSection(organization);
    
    return `
TERMS OF SERVICE - MEDBUILDER PLATFORM

Last Updated: ${currentDate}
Effective Date: ${contract.startDate}
Organization: ${organization.name}
Jurisdiction: ${jurisdiction}

1. ACCEPTANCE OF TERMS
By accessing and using the MedBuilder healthcare development platform ("Service"), ${organization.name} ("Customer", "you", or "your organization") agrees to be bound by these Terms of Service and all applicable laws and regulations.

2. SERVICE DESCRIPTION
MedBuilder provides AI-powered healthcare application development tools, including but not limited to:
- HIPAA-compliant application templates
- Healthcare-specific AI code generation
- Clinical decision support systems
- EHR/EMR integration capabilities
- Custom healthcare workflow automation

3. ORGANIZATION-SPECIFIC TERMS
Organization Type: ${organization.type}
Organization Size: ${organization.size}
Estimated Users: ${organization.estimatedUsers}
Primary Contact: ${organization.contactPerson} (${organization.contactTitle})

4. COMPLIANCE REQUIREMENTS
${complianceSection}

5. DATA PROCESSING AND PRIVACY
${dataProcessingSection}

6. ARTIFICIAL INTELLIGENCE USAGE
${aiUsageSection}

7. HEALTHCARE-SPECIFIC OBLIGATIONS
a) Patient Data Protection: Customer acknowledges that any patient health information (PHI) processed through the Service must comply with applicable healthcare privacy laws.
b) Clinical Decision Support: Any AI-generated clinical recommendations are for informational purposes only and must be reviewed by qualified healthcare professionals.
c) Medical Device Regulations: If Customer develops medical device software using the Service, Customer is responsible for FDA compliance and regulatory submissions.

8. SERVICE LEVEL AGREEMENT
- Uptime: 99.9% availability guarantee
- Support Response: <2 hours for critical healthcare issues
- Data Backup: Real-time backup with 99.999% durability
- Disaster Recovery: <4 hour RTO for critical systems

9. INTELLECTUAL PROPERTY
a) Platform IP: MedBuilder retains all rights to the platform technology and AI models.
b) Customer Content: Customer retains ownership of all applications, data, and content created using the Service.
c) Generated Code: Code generated by AI becomes Customer's property upon creation.

10. LIABILITY AND INDEMNIFICATION
Customer agrees to indemnify MedBuilder against claims arising from:
- Misuse of generated code in clinical settings
- Failure to obtain proper medical device approvals
- Non-compliance with applicable healthcare regulations
- Unauthorized use of patient data

11. TERMINATION
Either party may terminate with 30 days written notice. Upon termination:
- Customer retains all generated code and applications
- Data export capabilities provided for 90 days
- Compliance audit trail maintained for 7 years

12. GOVERNING LAW
These terms are governed by the laws of ${jurisdiction}, with disputes resolved through binding arbitration.

13. CONTACT INFORMATION
Legal Department: legal@medbuilder.com
Compliance Officer: compliance@medbuilder.com
Emergency Contact: +1-800-MEDBUILDER

By proceeding with the Service, ${organization.contactPerson} on behalf of ${organization.name} acknowledges having read, understood, and agreed to these terms.

Digital Signature Required: Yes
Contract ID: ${contract.id}
`;
  }

  // Generate dynamic Privacy Policy
  static generatePrivacyPolicy(organization: Organization): string {
    const currentDate = new Date().toLocaleDateString();
    const dataTypes = this.getDataTypesProcessed(organization);
    const retentionPeriods = this.getDataRetentionPeriods(organization);
    const crossBorderTransfers = this.getCrossBorderTransferRules(organization);
    
    return `
PRIVACY POLICY - MEDBUILDER PLATFORM

Last Updated: ${currentDate}
Organization: ${organization.name}
Jurisdiction: ${organization.country}

1. DATA CONTROLLER INFORMATION
MedBuilder Inc.
Healthcare Technology Division
Address: [Dynamic based on organization jurisdiction]
Contact: privacy@medbuilder.com
DPO: dpo@medbuilder.com (for GDPR compliance)

2. ORGANIZATION-SPECIFIC DATA PROCESSING
Organization: ${organization.name}
Contact Person: ${organization.contactPerson}
Business Purpose: Healthcare application development
Data Processing Basis: Legitimate business interest and contractual necessity

3. DATA TYPES COLLECTED AND PROCESSED
${dataTypes}

4. LAWFUL BASIS FOR PROCESSING
a) Contract Performance: Processing necessary for service delivery
b) Legitimate Interest: Platform improvement and security
c) Legal Compliance: Healthcare regulatory requirements
d) Consent: Where explicitly provided for specific features

5. DATA RETENTION PERIODS
${retentionPeriods}

6. INTERNATIONAL DATA TRANSFERS
${crossBorderTransfers}

7. HEALTHCARE-SPECIFIC PRIVACY PROTECTIONS
a) PHI Handling: All patient health information processed with HIPAA-compliant encryption
b) Clinical Data: Segregated storage with role-based access controls
c) Audit Trails: Complete audit logs for all data access and modifications
d) Breach Notification: Immediate notification for any suspected data breaches

8. INDIVIDUAL RIGHTS
You have the right to:
- Access your personal data
- Rectify inaccurate information
- Erase data (subject to legal retention requirements)
- Restrict processing
- Data portability
- Object to processing
- Withdraw consent

9. SECURITY MEASURES
- End-to-end encryption in transit and at rest
- Multi-factor authentication for all accounts
- Regular security audits and penetration testing
- SOC 2 Type II compliance
- ISO 27001 certified infrastructure

10. COOKIES AND TRACKING
Essential cookies only for platform functionality. No advertising or tracking cookies used.

11. CHILDREN'S PRIVACY
The Service is not intended for children under 13. We do not knowingly collect data from children.

12. CONTACT FOR PRIVACY MATTERS
Privacy Officer: privacy@medbuilder.com
Phone: +1-800-PRIVACY
Address: [Dynamic based on jurisdiction]

This policy is tailored for ${organization.name} and their specific compliance requirements.
`;
  }

  // Generate AI Usage Policy
  static generateAIUsagePolicy(organization: Organization): string {
    const currentDate = new Date().toLocaleDateString();
    const aiCapabilities = this.getAICapabilities(organization);
    const clinicalLimitations = this.getClinicalAILimitations(organization);
    
    return `
ARTIFICIAL INTELLIGENCE USAGE POLICY

Last Updated: ${currentDate}
Organization: ${organization.name}
AI Framework: MedBuilder Clinical AI Suite

1. AI SYSTEM OVERVIEW
MedBuilder employs advanced AI models specifically trained for healthcare applications:
- Healthcare BERT Models (ClinicalBERT, BioBERT, PubMedBERT)
- Medical NER and Classification Systems
- Clinical Decision Support AI
- HIPAA-Compliant Code Generation

2. ORGANIZATION-SPECIFIC AI CAPABILITIES
${aiCapabilities}

3. CLINICAL AI LIMITATIONS AND DISCLAIMERS
${clinicalLimitations}

4. DATA USAGE FOR AI TRAINING
a) Model Training: AI models are pre-trained on anonymized healthcare datasets
b) Customer Data: Your data is NEVER used to train AI models without explicit consent
c) Federated Learning: Optional participation in privacy-preserving model improvements
d) Data Anonymization: All training data is thoroughly de-identified

5. AI DECISION TRANSPARENCY
a) Explainable AI: Clinical AI provides reasoning for recommendations
b) Confidence Scores: All AI outputs include confidence levels
c) Source Attribution: References to medical literature when applicable
d) Human Oversight: AI recommendations require human review for clinical use

6. BIAS MITIGATION
a) Diverse Training Data: Models trained on diverse patient populations
b) Regular Bias Testing: Continuous monitoring for demographic bias
c) Fairness Metrics: Regular evaluation of AI fairness across populations
d) Cultural Competency: AI trained on multicultural healthcare practices

7. AI SAFETY MEASURES
a) Hallucination Prevention: Multiple validation layers to prevent AI errors
b) Medical Accuracy: AI outputs validated against medical knowledge bases
c) Fail-Safe Mechanisms: System defaults to human review for uncertain cases
d) Continuous Monitoring: Real-time monitoring of AI performance

8. INTELLECTUAL PROPERTY
a) AI-Generated Code: Becomes customer property upon generation
b) AI Models: Remain proprietary to MedBuilder
c) Training Data: Customer retains ownership of all submitted data
d) Derivative Works: Customer owns applications built using AI assistance

9. LIABILITY AND AI RECOMMENDATIONS
a) Tool Nature: AI provides assistance, not medical advice
b) Professional Responsibility: Healthcare professionals remain responsible for clinical decisions
c) Validation Required: All AI-generated content must be reviewed before clinical use
d) Regulatory Compliance: Customer responsible for FDA/regulatory approval if applicable

10. AI ETHICS COMPLIANCE
This AI system complies with:
- IEEE Standards for Ethical AI Design
- FDA Guidance on AI/ML-Based Medical Devices
- WHO Ethics and Governance of AI for Health
- AMA Guidelines on AI in Healthcare

11. CONTINUOUS IMPROVEMENT
AI models are continuously updated for:
- Medical knowledge advancement
- Performance optimization
- Security enhancements
- Regulatory compliance

For AI-related questions: ai-ethics@medbuilder.com
`;
  }

  // Generate Business Associate Agreement (HIPAA)
  static generateBusinessAssociateAgreement(organization: Organization, contract: Contract): string {
    const currentDate = new Date().toLocaleDateString();
    
    return `
BUSINESS ASSOCIATE AGREEMENT (HIPAA)

Effective Date: ${contract.startDate}
Covered Entity: ${organization.name}
Business Associate: MedBuilder Inc.

1. DEFINITIONS
Terms used but not defined in this Agreement have the meaning assigned to them in the HIPAA Privacy Rule at 45 CFR § 164.501.

2. PERMITTED USES AND DISCLOSURES
Business Associate may use and disclose PHI only to:
a) Perform services specified in the underlying Service Agreement
b) Provide healthcare application development services
c) Comply with legal requirements
d) Report security incidents as required by law

3. PROHIBITED USES AND DISCLOSURES
Business Associate shall NOT:
a) Use or disclose PHI for any purpose other than permitted uses
b) Use or disclose PHI in a manner that would violate the Privacy Rule
c) Use PHI for Business Associate's own purposes except as permitted

4. SAFEGUARDS
Business Associate shall:
a) Implement administrative, physical, and technical safeguards
b) Ensure PHI is encrypted in transit and at rest
c) Limit access to PHI to authorized personnel only
d) Maintain audit logs of all PHI access

5. SUBCONTRACTORS
Any subcontractors with PHI access must:
a) Enter into written agreements with equivalent protections
b) Be pre-approved by Covered Entity
c) Meet or exceed HIPAA security requirements

6. INDIVIDUAL RIGHTS
Business Associate shall:
a) Provide access to PHI as directed by Covered Entity
b) Amend PHI as directed by Covered Entity
c) Maintain accounting of disclosures
d) Support Covered Entity's compliance with individual rights

7. MINIMUM NECESSARY
Business Associate shall limit use and disclosure to the minimum necessary to accomplish the intended purpose.

8. BREACH NOTIFICATION
Business Associate shall:
a) Report breaches within 24 hours of discovery
b) Provide detailed breach assessment
c) Assist with breach notification requirements
d) Implement corrective measures immediately

9. RETURN OR DESTRUCTION OF PHI
Upon termination:
a) Return all PHI and copies within 30 days
b) If return not feasible, destroy PHI securely
c) Certify completion of return/destruction
d) Maintain protections for any retained PHI

10. COMPLIANCE MONITORING
a) Regular compliance audits
b) Security assessment reports
c) Incident response procedures
d) Staff training documentation

Authorized Signatures Required:

Covered Entity: ${organization.contactPerson}, ${organization.contactTitle}
Business Associate: [MedBuilder Authorized Representative]

Contract Reference: ${contract.id}
`;
  }

  // Helper methods for dynamic content generation
  private static getJurisdiction(state: string, country: string): string {
    if (country === "United States") {
      return `${state}, United States`;
    }
    return country;
  }

  private static generateComplianceSection(complianceNeeds: string[]): string {
    let section = "This service agreement incorporates the following compliance frameworks:\n\n";
    
    complianceNeeds.forEach(compliance => {
      switch (compliance) {
        case "HIPAA":
          section += "a) HIPAA Compliance: All PHI processed with appropriate safeguards, audit trails, and breach notification procedures.\n";
          break;
        case "GDPR":
          section += "b) GDPR Compliance: Data processing lawful basis established, individual rights supported, DPO available.\n";
          break;
        case "SOC 2":
          section += "c) SOC 2 Type II: Infrastructure meets security, availability, processing integrity, confidentiality, and privacy criteria.\n";
          break;
        case "FDA 21 CFR Part 11":
          section += "d) FDA 21 CFR Part 11: Electronic records and signatures meet FDA requirements for pharmaceutical applications.\n";
          break;
        default:
          section += `e) ${compliance}: Compliance measures implemented according to applicable standards.\n`;
      }
    });
    
    return section;
  }

  private static generateDataProcessingSection(organization: Organization): string {
    return `
Data Controller: ${organization.name}
Data Processor: MedBuilder Inc.
Processing Purpose: Healthcare application development and deployment
Data Categories: Application code, configuration data, user account information
Special Category Data: Healthcare/medical data (where applicable)
International Transfers: ${organization.country !== "United States" ? "Cross-border transfers with appropriate safeguards" : "Domestic processing within US"}
Retention Period: Active subscription period + 7 years for compliance audit trail
`;
  }

  private static generateAIUsageSection(organization: Organization): string {
    return `
AI Services Provided:
- Healthcare-specific code generation and optimization
- Clinical decision support recommendations (informational only)
- Medical terminology and standards integration
- HIPAA compliance checking and suggestions

AI Limitations:
- AI outputs require human review before clinical implementation
- Not a substitute for professional medical judgment
- Subject to continuous improvement and updates
- May not cover all edge cases or specialized medical scenarios

Data Usage for AI:
- Customer code and applications used only for service delivery
- No PHI used for AI model training without explicit consent
- Aggregated, anonymized usage patterns may inform platform improvements
- Customer retains full ownership of AI-generated content
`;
  }

  private static getDataTypesProcessed(organization: Organization): string {
    return `
Personal Data Categories Processed:
- User account information (name, email, role)
- Organization contact details
- Application development metadata
- Usage analytics (anonymized)
- Support communication records

Healthcare Data (if applicable):
- Medical terminology and coding systems
- Clinical workflow configurations
- De-identified test data sets
- FHIR resource templates

Technical Data:
- Application code and configurations
- API usage logs
- Security audit trails
- Performance metrics
`;
  }

  private static getDataRetentionPeriods(organization: Organization): string {
    const hasHealthcareData = organization.type.toLowerCase().includes('hospital') || 
                              organization.type.toLowerCase().includes('clinic') ||
                              organization.complianceNeeds.includes('HIPAA');
    
    return `
Data Retention Schedule:
- User account data: Duration of subscription + 30 days
- Application code: Duration of subscription + 90 days (for data portability)
- Audit logs: 7 years (compliance requirement)
- Support records: 3 years
${hasHealthcareData ? '- Healthcare/PHI data: As required by applicable healthcare regulations (typically 6+ years)' : ''}
- Backup data: 90 days after primary deletion
- Anonymized analytics: Indefinitely for platform improvement
`;
  }

  private static getCrossBorderTransferRules(organization: Organization): string {
    if (organization.country === "United States") {
      return `
Domestic Processing:
- Primary data processing within United States
- Cloud infrastructure in US regions
- No routine international transfers
- Emergency support may involve international teams with appropriate safeguards
`;
    }
    
    return `
International Data Transfers:
- Data processing may occur across multiple jurisdictions
- Appropriate safeguards implemented (Standard Contractual Clauses, adequacy decisions)
- Data localization options available for sensitive workloads
- Full data mapping provided upon request
`;
  }

  private static getAICapabilities(organization: Organization): string {
    let capabilities = `
AI Capabilities Available to ${organization.name}:
- Healthcare BERT for medical text analysis
- Clinical decision support recommendations
- Medical coding assistance (ICD-10, CPT, SNOMED CT)
- FHIR resource generation and validation
- Drug interaction checking and alerts
`;

    if (organization.complianceNeeds.includes('FDA 21 CFR Part 11')) {
      capabilities += "- FDA-compliant electronic signature workflows\n";
    }

    if (organization.integrationNeeds.includes('Epic') || organization.integrationNeeds.includes('Cerner')) {
      capabilities += "- EHR integration code generation\n";
    }

    return capabilities;
  }

  private static getClinicalAILimitations(organization: Organization): string {
    return `
IMPORTANT CLINICAL AI LIMITATIONS:

⚠️  MEDICAL DISCLAIMER: AI-generated clinical content is for informational purposes only and does not constitute medical advice, diagnosis, or treatment recommendations.

⚠️  PROFESSIONAL RESPONSIBILITY: Licensed healthcare professionals must review all AI outputs before clinical use.

⚠️  REGULATORY COMPLIANCE: Customer responsible for obtaining appropriate regulatory approvals for any AI-assisted medical devices or clinical decision support tools.

⚠️  VALIDATION REQUIRED: All AI-generated clinical algorithms must undergo appropriate validation and testing before patient care use.

⚠️  BIAS AWARENESS: AI models may contain biases; regular monitoring and human oversight required.

⚠️  NOT A MEDICAL DEVICE: MedBuilder AI is a development tool, not a cleared/approved medical device.
`;
  }
}