import { db } from "./db";
import { 
  publicTemplates, 
  showcases, 
  marketplaceTemplates, 
  courses,
  badges
} from "@shared/schema";

export async function seedViralGrowthData() {
  try {
    console.log('🌱 Seeding viral growth data...');

    await db.delete(publicTemplates);
    await db.delete(showcases);
    await db.delete(marketplaceTemplates);
    await db.delete(courses);
    await db.delete(badges);

    const publicTemplateData = [
      {
        templateId: 1,
        visibility: "public",
        shareSlug: "hipaa-patient-portal",
        ogTitle: "HIPAA Patient Portal",
        ogDescription: "Complete patient portal with secure messaging, appointment scheduling, and medical records access. Fully HIPAA compliant.",
        ogImage: "/templates/patient-portal.png",
        forkCount: 234,
        viewCount: 1892,
        likeCount: 156,
        authorName: "MedBuilder Team",
        tags: JSON.stringify(["hipaa", "patient-portal", "healthcare", "react"]),
        featuredAt: new Date(),
      },
      {
        templateId: 2,
        visibility: "public",
        shareSlug: "telehealth-video-platform",
        ogTitle: "Telehealth Video Platform",
        ogDescription: "HIPAA-compliant video consultation platform with waiting rooms, screen sharing, and EHR integration.",
        ogImage: "/templates/telehealth.png",
        forkCount: 189,
        viewCount: 1456,
        likeCount: 122,
        authorName: "Dr. Sarah Chen",
        tags: JSON.stringify(["telehealth", "video", "webrtc", "hipaa"]),
        featuredAt: new Date(),
      },
      {
        templateId: 3,
        visibility: "public",
        shareSlug: "fhir-integration-starter",
        ogTitle: "FHIR Integration Starter",
        ogDescription: "Connect to Epic, Cerner, and other EHRs with this FHIR R4 starter template. Includes patient data sync.",
        ogImage: "/templates/fhir.png",
        forkCount: 145,
        viewCount: 1123,
        likeCount: 98,
        authorName: "HL7 Community",
        tags: JSON.stringify(["fhir", "ehr", "epic", "cerner", "interoperability"]),
      },
      {
        templateId: 4,
        visibility: "public",
        shareSlug: "clinical-dashboard",
        ogTitle: "Clinical Dashboard",
        ogDescription: "Real-time clinical metrics dashboard with alerts, patient monitoring, and analytics visualization.",
        ogImage: "/templates/dashboard.png",
        forkCount: 167,
        viewCount: 1345,
        likeCount: 111,
        authorName: "MedBuilder Team",
        tags: JSON.stringify(["clinical", "dashboard", "analytics", "monitoring"]),
      },
      {
        templateId: 5,
        visibility: "public",
        shareSlug: "e-prescription-system",
        ogTitle: "E-Prescription System",
        ogDescription: "Electronic prescription management with drug interaction checking, pharmacy routing, and DEA compliance.",
        ogImage: "/templates/erx.png",
        forkCount: 89,
        viewCount: 876,
        likeCount: 67,
        authorName: "PharmaTech Labs",
        tags: JSON.stringify(["erx", "prescription", "pharmacy", "dea"]),
      },
      {
        templateId: 6,
        visibility: "public",
        shareSlug: "lab-results-viewer",
        ogTitle: "Lab Results Viewer",
        ogDescription: "Patient-friendly lab results display with trend charts, normal ranges, and physician notes.",
        ogImage: "/templates/labs.png",
        forkCount: 78,
        viewCount: 654,
        likeCount: 54,
        authorName: "LabCorp Connect",
        tags: JSON.stringify(["labs", "results", "patient", "visualization"]),
      },
    ];

    await db.insert(publicTemplates).values(publicTemplateData);
    console.log(`✅ Created ${publicTemplateData.length} public templates`);

    const showcaseData = [
      {
        projectId: 1,
        userId: "showcase-user-1",
        title: "CarePlus Telehealth",
        description: "A full-featured telehealth platform connecting patients with specialists across 15 healthcare systems. Includes video consultations, secure messaging, and prescription management.",
        shortDescription: "Enterprise telehealth for 15 healthcare systems",
        category: "telehealth",
        tags: JSON.stringify(["telehealth", "enterprise", "video"]),
        techStack: JSON.stringify(["React", "Node.js", "WebRTC", "PostgreSQL"]),
        likes: 342,
        views: 2341,
        forks: 45,
        isFeatured: true,
        featuredAt: new Date(),
        status: "approved",
        demoUrl: "https://demo.careplus.example.com",
      },
      {
        projectId: 2,
        userId: "showcase-user-2",
        title: "MedTrack Patient App",
        description: "Mobile-first patient engagement app with medication reminders, appointment booking, and health tracking. Used by 50,000+ patients.",
        shortDescription: "Patient engagement for 50k+ users",
        category: "patient",
        tags: JSON.stringify(["patient-app", "mobile", "engagement"]),
        techStack: JSON.stringify(["React Native", "Express", "MongoDB"]),
        likes: 287,
        views: 1876,
        forks: 38,
        isFeatured: true,
        featuredAt: new Date(),
        status: "approved",
        demoUrl: "https://medtrack.example.com",
      },
      {
        projectId: 3,
        userId: "showcase-user-3",
        title: "Clinical Trial Manager",
        description: "End-to-end clinical trial management system with patient recruitment, consent workflows, and FDA compliance reporting.",
        shortDescription: "FDA-compliant clinical trial platform",
        category: "research",
        tags: JSON.stringify(["clinical-trials", "fda", "research"]),
        techStack: JSON.stringify(["Vue.js", "Python", "PostgreSQL"]),
        likes: 198,
        views: 1234,
        forks: 23,
        status: "approved",
        demoUrl: "https://trials.example.com",
      },
      {
        projectId: 4,
        userId: "showcase-user-4",
        title: "Hospital Analytics Suite",
        description: "Real-time hospital operations dashboard with bed management, staff scheduling, and resource optimization algorithms.",
        shortDescription: "Real-time hospital operations",
        category: "admin",
        tags: JSON.stringify(["analytics", "hospital", "operations"]),
        techStack: JSON.stringify(["React", "Node.js", "TimescaleDB"]),
        likes: 156,
        views: 987,
        forks: 19,
        status: "approved",
        demoUrl: "https://analytics.example.com",
      },
      {
        projectId: 5,
        userId: "showcase-user-5",
        title: "Radiology AI Assistant",
        description: "AI-powered radiology screening tool that assists radiologists with preliminary reads and anomaly detection.",
        shortDescription: "AI-assisted radiology screening",
        category: "clinical",
        tags: JSON.stringify(["ai", "radiology", "imaging"]),
        techStack: JSON.stringify(["Python", "TensorFlow", "React", "DICOM"]),
        likes: 267,
        views: 1567,
        forks: 31,
        isFeatured: true,
        featuredAt: new Date(),
        status: "approved",
        demoUrl: "https://radai.example.com",
      },
    ];

    await db.insert(showcases).values(showcaseData);
    console.log(`✅ Created ${showcaseData.length} showcases`);

    const marketplaceData = [
      {
        templateId: 1,
        sellerId: "seller-medbuilder",
        title: "Enterprise Patient Portal Pro",
        description: "Complete enterprise patient portal with SSO, multi-tenancy, and advanced analytics.",
        longDescription: "Our most comprehensive patient portal solution includes single sign-on integration, white-label customization, advanced analytics dashboard, and full HIPAA compliance documentation.",
        price: 29900,
        category: "templates",
        tags: JSON.stringify(["enterprise", "portal", "sso"]),
        downloads: 156,
        rating: 480,
        reviewCount: 42,
        status: "approved",
        featuredAt: new Date(),
      },
      {
        templateId: 2,
        sellerId: "seller-medbuilder",
        title: "Telehealth Starter Kit",
        description: "Everything you need to launch a telehealth service in days, not months.",
        price: 0,
        category: "templates",
        tags: JSON.stringify(["telehealth", "starter", "free"]),
        downloads: 2341,
        rating: 450,
        reviewCount: 178,
        status: "approved",
      },
      {
        templateId: 3,
        sellerId: "seller-community",
        title: "FHIR Component Library",
        description: "50+ reusable React components for FHIR R4 data display and forms.",
        price: 7900,
        category: "components",
        tags: JSON.stringify(["fhir", "components", "react"]),
        downloads: 423,
        rating: 490,
        reviewCount: 67,
        status: "approved",
      },
      {
        templateId: 4,
        sellerId: "seller-community",
        title: "Healthcare Dark Theme",
        description: "Professional dark theme optimized for clinical environments with reduced eye strain.",
        price: 1900,
        category: "themes",
        tags: JSON.stringify(["theme", "dark-mode", "clinical"]),
        downloads: 876,
        rating: 460,
        reviewCount: 89,
        status: "approved",
      },
      {
        templateId: 5,
        sellerId: "seller-medbuilder",
        title: "Epic FHIR Integration Kit",
        description: "Pre-built integration for Epic MyChart with patient data sync and OAuth flows.",
        price: 49900,
        category: "integrations",
        tags: JSON.stringify(["epic", "fhir", "integration"]),
        downloads: 89,
        rating: 500,
        reviewCount: 23,
        status: "approved",
        featuredAt: new Date(),
      },
      {
        templateId: 6,
        sellerId: "seller-community",
        title: "Medical Forms Collection",
        description: "100+ validated medical intake forms with accessibility compliance.",
        price: 3900,
        category: "templates",
        tags: JSON.stringify(["forms", "intake", "accessibility"]),
        downloads: 567,
        rating: 440,
        reviewCount: 56,
        status: "approved",
      },
    ];

    await db.insert(marketplaceTemplates).values(marketplaceData);
    console.log(`✅ Created ${marketplaceData.length} marketplace templates`);

    const courseData = [
      {
        slug: "hipaa-fundamentals",
        title: "HIPAA Fundamentals for Developers",
        description: "Master the essentials of HIPAA compliance for healthcare software development. Learn about PHI handling, security requirements, and audit preparation.",
        shortDescription: "Essential HIPAA knowledge for healthcare developers",
        instructorName: "Dr. Michael Chen",
        category: "hipaa",
        difficulty: "beginner",
        duration: 180,
        lessonCount: 12,
        enrollmentCount: 2456,
        rating: 480,
        reviewCount: 234,
        price: 0,
        isFree: true,
        isFeatured: true,
        isPublished: true,
        skills: JSON.stringify(["HIPAA Compliance", "PHI Handling", "Security Controls"]),
      },
      {
        slug: "fhir-api-development",
        title: "Building FHIR APIs from Scratch",
        description: "Learn to build HL7 FHIR R4 compliant APIs. Covers resources, profiles, operations, and integration with major EHR systems.",
        shortDescription: "Complete FHIR API development course",
        instructorName: "Sarah Williams",
        category: "development",
        difficulty: "intermediate",
        duration: 360,
        lessonCount: 24,
        enrollmentCount: 1234,
        rating: 490,
        reviewCount: 156,
        price: 9900,
        isFree: false,
        isPublished: true,
        skills: JSON.stringify(["FHIR R4", "API Development", "EHR Integration"]),
      },
      {
        slug: "telehealth-architecture",
        title: "Telehealth Platform Architecture",
        description: "Design scalable, HIPAA-compliant telehealth systems. Covers WebRTC, video infrastructure, and real-time communication patterns.",
        shortDescription: "Design enterprise telehealth systems",
        instructorName: "Alex Rodriguez",
        category: "development",
        difficulty: "advanced",
        duration: 420,
        lessonCount: 18,
        enrollmentCount: 876,
        rating: 470,
        reviewCount: 89,
        price: 14900,
        isFree: false,
        isPublished: true,
        skills: JSON.stringify(["WebRTC", "Video Streaming", "System Architecture"]),
      },
      {
        slug: "clinical-data-models",
        title: "Clinical Data Modeling",
        description: "Learn to design healthcare databases that support clinical workflows. Covers SNOMED, ICD-10, LOINC, and clinical terminology systems.",
        shortDescription: "Healthcare database design fundamentals",
        instructorName: "Dr. Emily Park",
        category: "clinical",
        difficulty: "intermediate",
        duration: 240,
        lessonCount: 16,
        enrollmentCount: 654,
        rating: 460,
        reviewCount: 67,
        price: 0,
        isFree: true,
        isPublished: true,
        skills: JSON.stringify(["Data Modeling", "SNOMED CT", "ICD-10", "LOINC"]),
      },
      {
        slug: "hipaa-security-certification",
        title: "HIPAA Security Professional Certification",
        description: "Comprehensive certification course covering all aspects of HIPAA Security Rule. Prepare for compliance audits and earn your certification.",
        shortDescription: "Official HIPAA security certification",
        instructorName: "MedBuilder Academy",
        category: "certification",
        difficulty: "advanced",
        duration: 600,
        lessonCount: 32,
        enrollmentCount: 2100,
        rating: 495,
        reviewCount: 312,
        price: 29900,
        isFree: false,
        isFeatured: true,
        isPublished: true,
        skills: JSON.stringify(["HIPAA Security", "Risk Assessment", "Compliance Audit"]),
        certification: JSON.stringify({
          name: "Certified HIPAA Security Professional",
          issuer: "MedBuilder Academy",
          validFor: "2 years",
        }),
      },
      {
        slug: "react-healthcare-ui",
        title: "Building Healthcare UIs with React",
        description: "Create accessible, compliant healthcare interfaces. Covers clinical forms, patient dashboards, and medical data visualization.",
        shortDescription: "Healthcare UI development with React",
        instructorName: "Jordan Lee",
        category: "development",
        difficulty: "beginner",
        duration: 300,
        lessonCount: 20,
        enrollmentCount: 1567,
        rating: 475,
        reviewCount: 189,
        price: 0,
        isFree: true,
        isPublished: true,
        skills: JSON.stringify(["React", "Accessibility", "Healthcare UI"]),
      },
    ];

    await db.insert(courses).values(courseData);
    console.log(`✅ Created ${courseData.length} courses`);

    const badgeData = [
      {
        code: "hipaa-certified",
        name: "HIPAA Certified Developer",
        description: "Completed HIPAA certification course with passing score",
        iconName: "Shield",
        category: "certification",
        tier: "gold",
        points: 500,
        isActive: true,
      },
      {
        code: "first-project",
        name: "First Project",
        description: "Created your first MedBuilder project",
        iconName: "Rocket",
        category: "achievement",
        tier: "bronze",
        points: 50,
        isActive: true,
      },
      {
        code: "template-creator",
        name: "Template Creator",
        description: "Published a template to the community gallery",
        iconName: "FileCode",
        category: "contribution",
        tier: "silver",
        points: 200,
        isActive: true,
      },
      {
        code: "community-helper",
        name: "Community Helper",
        description: "Helped 10+ community members with their projects",
        iconName: "Users",
        category: "contribution",
        tier: "silver",
        points: 150,
        isActive: true,
      },
      {
        code: "fhir-expert",
        name: "FHIR Expert",
        description: "Completed all FHIR development courses",
        iconName: "Database",
        category: "skill",
        tier: "gold",
        points: 300,
        isActive: true,
      },
    ];

    await db.insert(badges).values(badgeData);
    console.log(`✅ Created ${badgeData.length} badges`);

    console.log('🎉 Viral growth seeding complete!');

  } catch (error) {
    console.error('❌ Error seeding viral growth data:', error);
    throw error;
  }
}
